"""WebSocket chat routes and session history API."""

from __future__ import annotations

import mimetypes
import os
import re
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any
from uuid import uuid4

from fastapi import APIRouter, File, Query, UploadFile, WebSocket, WebSocketDisconnect
from fastapi.responses import FileResponse, HTMLResponse, PlainTextResponse

from onboard.services.chat_service import stream_chat

router = APIRouter(tags=["chat"])

_UPLOAD_DIR = Path(os.environ.get("ONBOARD_WORKSPACE", "~/.onboard")).expanduser() / "chat-uploads"
_MAX_UPLOAD_SIZE = 20 * 1024 * 1024  # 20 MB

# Regex to strip the volatile time-context prefix injected by the runner
_TIME_CONTEXT_RE = re.compile(
    r"^## Current Local Time\n(?:- [^\n]+\n)+\n.*?\n+---\n+",
    re.DOTALL,
)


def _strip_time_context(text: str) -> str:
    """Remove the runner's time-context header from a user message."""
    return _TIME_CONTEXT_RE.sub("", text, count=1)


def _get_workspace(app_name: str) -> Path:
    if app_name == "solo":
        from solo.core.workspace import get_workspace_root
        return get_workspace_root(None)
    else:
        from wolo.core.workspace import get_workspace_root
        return get_workspace_root(None)


def _get_session_module(app_name: str):
    if app_name == "solo":
        from solo.core import session
        return session
    else:
        from wolo.core import session
        return session


@router.post("/api/chat/upload")
async def upload_chat_file(file: UploadFile = File(...)) -> dict[str, str]:
    """Upload a file for use in chat. Returns the URL path and the disk path."""
    _UPLOAD_DIR.mkdir(parents=True, exist_ok=True)
    safe_name = re.sub(r"[^\w.\-]", "_", file.filename or "upload")
    stored_name = f"{uuid4().hex[:12]}_{safe_name}"
    disk_path = _UPLOAD_DIR / stored_name
    data = await file.read()
    if len(data) > _MAX_UPLOAD_SIZE:
        from fastapi import HTTPException
        raise HTTPException(413, "File too large (max 20 MB)")
    disk_path.write_bytes(data)
    url_path = f"/api/chat/uploads/{stored_name}"
    return {"path": url_path, "disk_path": str(disk_path)}


@router.get("/api/chat/uploads/{filename}")
def serve_uploaded_file(filename: str) -> FileResponse:
    """Serve an uploaded chat file."""
    file_path = (_UPLOAD_DIR / filename).resolve()
    if not file_path.is_relative_to(_UPLOAD_DIR.resolve()) or not file_path.is_file():
        from fastapi import HTTPException
        raise HTTPException(404, "File not found")
    content_type, _ = mimetypes.guess_type(str(file_path))
    return FileResponse(file_path, media_type=content_type or "application/octet-stream")


@router.get("/api/chat/media")
def serve_chat_media(path: str) -> FileResponse:
    """Serve a media file generated by a tool."""
    file_path = Path(path).resolve()
    if not file_path.is_file():
        from fastapi import HTTPException
        raise HTTPException(404, "File not found")
    content_type, _ = mimetypes.guess_type(str(file_path))
    return FileResponse(file_path, media_type=content_type or "application/octet-stream")


@router.websocket("/ws/chat/{app_name}")
async def chat(websocket: WebSocket, app_name: str) -> None:
    await websocket.accept()
    session_key = websocket.query_params.get("session") or f"web-{uuid4().hex[:12]}"
    # Notify client of assigned session key
    await websocket.send_json({"type": "session_key", "session_key": session_key})
    try:
        while True:
            message = await websocket.receive_json()
            message_type = message.get("type")
            if message_type == "cancel":
                await websocket.send_json({"type": "complete", "content": ""})
                continue
            if message_type != "message":
                await websocket.send_json({"type": "error", "message": "Unsupported message type"})
                continue
            content = str(message.get("content") or "").strip()
            media_raw = message.get("media")
            media = [str(p) for p in media_raw if isinstance(p, str) and p.strip()] if isinstance(media_raw, list) else []
            if not content and not media:
                await websocket.send_json({"type": "error", "message": "Message content or media is required"})
                continue
            try:
                async for event in stream_chat(app_name, content, session_key=session_key, media=media or None):
                    await websocket.send_json(event)
            except Exception as exc:
                await websocket.send_json({"type": "error", "message": str(exc)})
    except WebSocketDisconnect:
        return


@router.get("/api/{app_name}/chat/sessions")
def list_sessions(
    app_name: str,
    limit: int = Query(50, ge=1, le=200),
    search: str | None = Query(None),
) -> list[dict[str, Any]]:
    """List recent chat sessions (within 30 days, web-originated only)."""
    session_mod = _get_session_module(app_name)
    workspace = _get_workspace(app_name)
    sessions = session_mod.list_conversations(workspace, limit=limit)

    # Only show sessions created by the web UI (session_key starts with "web-")
    sessions = [s for s in sessions if s.get("session_key", "").startswith("web-")]

    # Filter to last 30 days
    cutoff = (datetime.now(timezone.utc) - timedelta(days=30)).isoformat()
    sessions = [s for s in sessions if (s.get("updated_at") or "") >= cutoff]

    # Search by keyword in first user message (preview)
    if search:
        keyword = search.lower()
        filtered = []
        for s in sessions:
            messages, _ = session_mod.load_conversation(workspace, s["session_key"])
            preview = next((_strip_time_context(m.text)[:100] for m in messages if m.role == "user" and m.text.strip()), "")
            if keyword in preview.lower():
                s["preview"] = preview
                filtered.append(s)
            else:
                # Also search assistant responses
                for m in messages:
                    if m.text and keyword in m.text.lower():
                        s["preview"] = preview
                        filtered.append(s)
                        break
        sessions = filtered
    else:
        # Add preview (first user message) for display
        for s in sessions:
            messages, _ = session_mod.load_conversation(workspace, s["session_key"])
            s["preview"] = next((_strip_time_context(m.text)[:100] for m in messages if m.role == "user" and m.text.strip()), "")

    return sessions


@router.get("/api/{app_name}/chat/sessions/{session_key}")
def get_session(app_name: str, session_key: str) -> dict[str, Any]:
    """Get full message history for a session."""
    session_mod = _get_session_module(app_name)
    workspace = _get_workspace(app_name)
    messages, session_id = session_mod.load_conversation(workspace, session_key)
    return {
        "session_key": session_key,
        "session_id": session_id,
        "messages": [
            {"role": m.role, "content": _strip_time_context(m.text) if m.role == "user" else m.text}
            for m in messages
            if m.role in ("user", "assistant") and m.text.strip()
        ],
    }


@router.delete("/api/{app_name}/chat/sessions/{session_key}")
def delete_session(app_name: str, session_key: str) -> dict[str, bool]:
    """Delete a chat session."""
    session_mod = _get_session_module(app_name)
    workspace = _get_workspace(app_name)
    conn = session_mod._get_db(workspace)
    try:
        cur = conn.execute("DELETE FROM conversations WHERE session_key = ?", (session_key,))
        conn.commit()
        return {"deleted": cur.rowcount > 0}
    finally:
        conn.close()


@router.get("/api/{app_name}/chat/sessions/{session_key}/export/markdown")
def export_markdown(app_name: str, session_key: str) -> PlainTextResponse:
    """Export a session as formatted Markdown."""
    session_mod = _get_session_module(app_name)
    workspace = _get_workspace(app_name)
    messages, _ = session_mod.load_conversation(workspace, session_key)

    lines = [f"# Chat Session: {session_key}\n"]
    for m in messages:
        if not m.text.strip():
            continue
        if m.role == "user":
            lines.append(f"## 🧑 User\n\n{m.text.strip()}\n")
        elif m.role == "assistant":
            lines.append(f"## 🤖 Assistant\n\n{m.text.strip()}\n")

    content = "\n".join(lines)
    return PlainTextResponse(
        content,
        media_type="text/markdown; charset=utf-8",
        headers={"Content-Disposition": f'attachment; filename="chat-{session_key}.md"'},
    )


@router.get("/api/{app_name}/chat/sessions/{session_key}/export/html")
def export_html(app_name: str, session_key: str) -> HTMLResponse:
    """Export a session as formatted HTML."""
    session_mod = _get_session_module(app_name)
    workspace = _get_workspace(app_name)
    messages, _ = session_mod.load_conversation(workspace, session_key)

    msg_blocks: list[str] = []
    for m in messages:
        if not m.text.strip():
            continue
        escaped = m.text.strip().replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        if m.role == "user":
            msg_blocks.append(
                f'<div class="msg user"><div class="label">🧑 User</div><div class="content">{escaped}</div></div>'
            )
        elif m.role == "assistant":
            msg_blocks.append(
                f'<div class="msg assistant"><div class="label">🤖 Assistant</div><div class="content">{escaped}</div></div>'
            )

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Chat: {session_key}</title>
<style>
body {{ font-family: -apple-system, system-ui, sans-serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; background: #0a0a0f; color: #e4e4e7; }}
h1 {{ font-size: 1.4rem; border-bottom: 1px solid #2e2e33; padding-bottom: 0.5rem; }}
.msg {{ margin: 1.5rem 0; padding: 1rem; border-radius: 8px; }}
.msg.user {{ background: #1c1917; border-left: 3px solid #d4a574; }}
.msg.assistant {{ background: #1c1c21; border-left: 3px solid #5eead4; }}
.label {{ font-size: 0.75rem; font-weight: 600; margin-bottom: 0.5rem; opacity: 0.7; }}
.content {{ white-space: pre-wrap; line-height: 1.6; }}
</style>
</head>
<body>
<h1>Chat Session: {session_key}</h1>
{"".join(msg_blocks)}
</body>
</html>"""
    return HTMLResponse(
        html,
        headers={"Content-Disposition": f'attachment; filename="chat-{session_key}.html"'},
    )
